CC = gcc
CFLAGS = -Wall -Werror

SRCS = main.c fsieve/fsieve.c fsieve/fsieve.c
OBJS = $(SRCS:.c=.o)
DEPS = $(SRCS:.c=.h)

TARGET = operating_system_pipes

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(TARGET)

%.o: %.c $(DEPS)
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)

.PHONY: all clean
